{
  "_url": "https://github.com/PowerShell/PowerShell/issues/10451",
  "author": "KirkMunro",
  "body": "# Steps to reproduce\r\n\r\n```powershell\r\n$error.Clear()\r\ngcm Get-InvalidCommand\r\n$error.Count\r\n```\r\n\r\n# Expected behavior\r\n\r\n```none\r\n1\r\n```\r\n\r\n# Actual behavior\r\n\r\n```none\r\n2\r\n```\r\n\r\n# Root cause\r\n\r\nThis bug is caused by [this line of code](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs#L72). That was written to assume that matches would be found, but matches are not always found. The script needs to capture the results of the fuzzy search first, and it should only return a string if it found matches.\r\n\r\n# Environment data\r\n\r\nThis was actually done using a build of preview 3. I just haven't updated my tags, but this is using the latest version available at the time of posting.\r\n\r\n```none\r\nName                           Value\r\n----                           -----\r\nPSVersion                      7.0.0-preview.2\r\nPSEdition                      Core\r\nGitCommitId                    7.0.0-preview.2-79-g3943f18c28e9df8369ef17776467c732648747b8\r\nOS                             Microsoft Windows 10.0.17763\r\nPlatform                       Win32NT\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u2026}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\r\n```\r\n",
  "closed_at": null,
  "comments": [
    {
      "author": "KirkMunro",
      "author_association": "CONTRIBUTOR",
      "body": "cc: @vexx32 (since you mentioned you have some WIP in a PR in this area)",
      "created_at": "2019-08-27T15:16:00Z",
      "updated_at": "2019-08-27T15:16:00Z"
    },
    {
      "author": "vexx32",
      "author_association": "COLLABORATOR",
      "body": "I think the WIP PR I mentioned actually had to tackle that already. (#9115 for context)\r\n\r\nThe CommandNotFoundException is a bit of an odd duck, it has the ErrorRecord as a _property_ of the exception. A bit of careless coding on my part actually resulted in this becoming an infinite loop. Took me quite a while to figure _that_ one out. CI would just... endlessly stall when it reached those tests, so believe I handled it by necessity in there.\r\n\r\nMightn't have been the best handling, I may need to revisit it and ensure I've not overcomplicated it or something, but yeah. \ud83d\ude42 \r\n\r\nThanks for the heads up! \ud83d\ude0a ",
      "created_at": "2019-08-27T15:28:25Z",
      "updated_at": "2019-08-27T15:35:23Z"
    }
  ],
  "created_at": "2019-08-27T15:01:16Z",
  "number": 10451,
  "state": "open",
  "title": "`PSCommandNotFoundSuggestion` generates an error when it fails to find a match.",
  "updated_at": "2019-09-03T12:34:42Z"
}