{
  "_url": "https://github.com/PowerShell/PowerShell/issues/5082",
  "author": "yuyixuantai",
  "body": "<!--\r\n\r\nIf it is a bug report:\r\n- make sure you are able to repro it on the latest released version. \r\nYou can install the latest version from https://github.com/PowerShell/PowerShell/releases\r\n- Search the existing issues.\r\n- Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).\r\n- Refer to the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md).\r\n- Fill out the following repro template\r\n\r\nIf it's not a bug, please remove the template and elaborate the issue in your own words.\r\n-->\r\n\r\nSteps to reproduce\r\n------------------\r\n\r\n```powershell\r\n\r\n```\r\n1. cd dir:\r\nPS C:\\Program Files\\PowerShell\\6.0.0-beta.8> cd D:\\code\\py\\google-python-exercises\\john\r\n2. start python in powershell\r\nPS D:\\code\\py\\google-python-exercises\\john> python\r\n3. use help function:\r\n help(dict)\r\n\r\nExpected behavior\r\n-----------------\r\n\r\n```none\r\n\r\n```\r\ndisplay next text:\r\nHelp on class dict in module __builtin__:\r\nclass dict(object)\r\n |  dict() -> new empty dictionary\r\n |  dict(mapping) -> new dictionary initialized from a mapping object's\r\n |      (key, value) pairs\r\n |  dict(iterable) -> new dictionary initialized as if via:\r\n |      d = {}\r\n |      for k, v in iterable:\r\n |          d[k] = v\r\nIn python 2.7.13, is ok:\r\n![20171011150552](https://user-images.githubusercontent.com/13009510/31426385-b6cbcc4c-ae95-11e7-9cc0-05b702f1ffea.png)\r\n![20171011150154](https://user-images.githubusercontent.com/13009510/31426266-2cdd5190-ae95-11e7-9a4d-b9ba0f6137c8.png)\r\nActual behavior\r\n---------------\r\n\r\n```none\r\n\r\n```\r\n1. if there is a file <string.pyc>, display:\r\nhello\r\nHELLO\r\nHello\r\n1\r\ne\r\no\r\nH\r\no\r\nl\r\nel\r\nHello\r\nI want code string I have 100 time\r\n\r\n2. if there has no file named <string.pyc>:\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Python27\\lib\\site.py\", line 445, in __call__\r\n    import pydoc\r\n  File \"C:\\Python27\\lib\\pydoc.py\", line 58, in <module>\r\n    from string import expandtabs, find, join, lower, split, strip, rfind, rstrip\r\nImportError: cannot import name expandtabs\r\n\r\n![20171011150204](https://user-images.githubusercontent.com/13009510/31426267-2d139142-ae95-11e7-97bf-e2301ba64167.png)\r\nEnvironment data\r\n----------------\r\nName                           Value\r\n----                           -----\r\nPSVersion                      6.0.0-beta.8\r\nPSEdition                      Core\r\nGitCommitId                    v6.0.0-beta.8\r\nOS                             Microsoft Windows 10.0.14393\r\nPlatform                       Win32NT\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\r\n<!-- provide the output of $PSVersionTable -->\r\n\r\n```powershell\r\n> $PSVersionTable\r\n\r\n```\r\n",
  "closed_at": "2017-10-11T17:34:17Z",
  "comments": [
    {
      "author": "markekraus",
      "author_association": "CONTRIBUTOR",
      "body": "I can't reproduce this with Python 2.7.14 ( I don't have 2.7.13 handy to test with). But that output seems to indicate to me you are not working with a clean python environment.  Also, you are running the alias `python` which could be resolving to something else.\r\n\r\nCan you try running the python.exe from its full path name from the ptython install folder?\r\n\r\n```powershell\r\nset-location c:\\Python27\\\r\nC:\\Python27\\python.exe\r\n```\r\n\r\nand then run \r\n\r\n```python\r\nhelp(dict)\r\n```\r\n\r\nAnd see if you get the same results?\r\n\r\n![2017101101](https://user-images.githubusercontent.com/6509955/31430383-4cc4803c-ae36-11e7-85d8-94bfa051dbb8.PNG)\r\n",
      "created_at": "2017-10-11T08:43:19Z",
      "updated_at": "2017-10-11T08:44:40Z"
    },
    {
      "author": "MaximoTrinidad",
      "author_association": "NONE",
      "body": "Although, I got Windows 10 Build 15063, I just installed Python 2.7.12 selecting to install all features. \r\nAnd, was able to execute the \"help(dict)\" command without any issues in both DOS and PowerShell Core Beta.8 shells.\r\n\r\nMy suggestion would be to reinstall Python 2.7.12 with all features, then try again.  Remember to \"unblock\" the MSI file before installing.\r\n\r\n![poshpython2 7 12_2017-10-11_9-46-15](https://user-images.githubusercontent.com/19892435/31444278-c0928936-ae69-11e7-93be-12fbaec9f046.png)\r\n",
      "created_at": "2017-10-11T13:53:06Z",
      "updated_at": "2017-10-11T13:53:06Z"
    },
    {
      "author": "yuyixuantai",
      "author_association": "NONE",
      "body": "@markekraus @MaximoTrinidad  @SteveL-MSFT I installed Python 2.7.14 and I can reproduce it every time. and now I kown the reason and avoid it.\r\nSteps to reproduce:\r\n1. cd a new path:\r\n    cd D:\\code\\pytest\r\n    in \"D:\\code\\pytest\", there is only one file **string.py  (this is bug source)**\r\n2. start python in current path:\r\n    path\r\n3. help(dict)\r\n![bugwithstring](https://user-images.githubusercontent.com/13009510/31474567-3855b24e-af2e-11e7-9cc3-0b1decc81cbc.png)\r\n\r\n4. **del string.py**, exit python then restart python, help(dict) run ok: \r\n![helpfuncwithnostring](https://user-images.githubusercontent.com/13009510/31474668-c0746b8e-af2e-11e7-9882-f57072682af5.png)\r\n\r\n\r\npython import string.py in current path 1st\uff0cand import orther module in lib path next\u3002the string.py dirty python environment. \r\n\r\n",
      "created_at": "2017-10-12T01:25:34Z",
      "updated_at": "2017-10-12T01:25:34Z"
    },
    {
      "author": "MaximoTrinidad",
      "author_association": "NONE",
      "body": "@yuyixuantai, Thanks for the update!\r\n:)\r\n",
      "created_at": "2017-10-12T14:12:13Z",
      "updated_at": "2017-10-12T14:12:13Z"
    }
  ],
  "created_at": "2017-10-11T07:07:01Z",
  "labels": [
    "Issue-Question",
    "Resolution-Answered"
  ],
  "number": 5082,
  "state": "closed",
  "title": "python function error ",
  "updated_at": "2017-10-12T14:12:13Z"
}